[[colors.indexed_colors]]
color = "0x000000"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x15161E"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12.0
bold.family = "Fira Code Nerd Font"
bold_italic.family = "Fira Code Nerd Font"
italic.family = "Fira Code Nerd Font"
normal.family = "Fira Code Nerd Font"

[shell]
program = "/usr/bin/fish"

[window]
dynamic_title = false
opacity = 0.5
title = "Alacritty"

[window.dimensions]
columns = 100
lines = 35

[window.padding]
x = 5
y = 5
