# Add symbolic link with PowerShell
# New-Item -ItemType SymbolicLink -Path $env:HOMEPATH\.starship\config.toml -Target "$env:HOMEPATH\Documents\repos\.dotfiles\starship\starship.toml"

format = "$all"

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vicmd_symbol = "[V](bold green) "

[directory]
truncation_length = 1

[aws]
disabled = true
