# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
 
# Disable the blank line at the start of the prompt
add_newline = false
 
[character]
success_symbol = "[|](bold red)"
error_symbol = "[|](bold red)"
vicmd_symbol = "[V](bold green)"

[line_break]
disabled = true
 
[directory]
style = 'bold yellow'
truncation_length = 1

[git_branch]
style = 'bold green'
format = 'on [$branch(:$remote_branch)]($style) '

[git_commit]
style = 'bold green'

[git_state]
style = 'bold green'

[git_status]
style = 'bold green'
format = '([\($all_status$ahead_behind\)]($style) )'
deleted = 'x'

[package]
disabled = true

[python]
format = '[(\($virtualenv\) )]($style)'

[nodejs]
disabled = true
